# Generated by Django 5.1.6 on 2025-03-03 15:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "photo",
                    models.URLField(
                        blank=True, null=True, verbose_name="Фото"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Английское название",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "photo",
                    models.URLField(
                        blank=True, null=True, verbose_name="Фото"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Английское название",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact", models.TextField(verbose_name="Текст факта")),
                (
                    "is_spoiler",
                    models.BooleanField(
                        default=False, verbose_name="Это спойлер"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.FloatField(verbose_name="Год релиза")),
                ("rating", models.IntegerField(verbose_name="Рейтинг")),
                (
                    "poster",
                    models.URLField(
                        blank=True, null=True, verbose_name="Постер"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Английское название",
                    ),
                ),
                (
                    "alternative_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Альтернативное название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Фильм"),
                            ("tv-series", "Сериал"),
                            ("cartoon", "Мультфильм"),
                            ("anime", "Аниме"),
                            ("animated-series", "Мульт сериал"),
                            ("tv-show", "Телешоу"),
                        ],
                        max_length=50,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        size=None,
                        verbose_name="Жанры",
                    ),
                ),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Страны",
                    ),
                ),
                (
                    "trailer",
                    models.URLField(
                        blank=True, null=True, verbose_name="Трейлер"
                    ),
                ),
                (
                    "watch",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на ресурс для просмотра",
                    ),
                ),
                (
                    "movie_length",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Длина фильма в минутах",
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="films",
                        to="films.actor",
                        verbose_name="Актеры",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director",
                        to="films.director",
                        verbose_name="Режиссер",
                    ),
                ),
            ],
        ),
    ]
