# Generated by Django 5.1.6 on 2025-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.FloatField(verbose_name="Рейтинг"),
        ),
    ]
