# Generated by Django 5.1.6 on 2025-03-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0003_alter_film_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="year",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Год релиза"
            ),
        ),
    ]
