name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Update this with your default branch if needed
  pull_request:

jobs:
  flake8-check:
    runs-on: ubuntu-latest
    container: python:3.13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq postgresql-client
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Flake8
        run: |
          cd backend/
          flake8 .

  django-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test123
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - "5432:5432"
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq postgresql-client
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Tests
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test123
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          cd backend/src
          python3 manage.py test
